name: Python

on:
  pull_request:
    paths:
      - "data/scrapers/src/**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        working-directory: data/scrapers
        run: |
          poetry install --only dev

      - name: Run ruff - static analysis
        working-directory: data/scrapers
        run: |
          poetry run ruff check

  lint-imports:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        working-directory: data/scrapers
        run: |
          poetry install --only dev

      - name: Run import linter
        working-directory: data/scrapers
        run: |
          poetry run lint-imports

  pytest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        working-directory: data/scrapers
        run: |
          poetry install --without ml

      - name: Run pytest
        working-directory: data/scrapers
        # TODO https://github.com/SzymonPajzert/koryta/issues/196
        run: |
          poetry run pytest --ignore src/tests 
  
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        working-directory: data/scrapers
        run: |
          poetry install --without ml

      - name: Run mypy
        working-directory: data/scrapers
        run: poetry run mypy src

  
